name: sisfo_sarpras
description: "Project hitam"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
